name: 'MiniProgram'
description: 'A GitHub Action to build MiniProgram.'
author: 'Anguer'

branding:
  icon: 'package'
  color: 'red'

inputs:
  root:
    description: 'Root directory of your project'
    required: false
    default: '.'
  version:
    description: 'Version of your MiniProgram'
    required: false
    default: '1.0.0'
  description:
    description: 'Description of your MiniProgram'
    required: false
    default: 'MiniProgram'

outputs:
  version:
    description: 'Version of your MiniProgram'

runs:
  using: node20
  main: dist/index.js
