name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install deps
        run: pnpm install

      - name: Check Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          root: ./miniprogram/wechat
          version: 1.0.0
          description: test
        env:
          WECHAT_MINI_PROGRAM_PRIVATE_KEY: ${{ secrets.WECHAT_MINI_PROGRAM_PRIVATE_KEY }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.version }}"

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #      - name: Install Node.js
      #        uses: actions/setup-node@v4
      #        with:
      #          node-version: 20
      #
      #      - name: Install pnpm
      #        uses: pnpm/action-setup@v3
      #        with:
      #          version: 8
      #          run_install: false
      #
      #      - name: Install deps
      #        run: pnpm install

      - name: Release
        run: pnpm release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
